#Adapted from http://gronlier.fr/blog/2015/01/adding-code-coverage-to-your-c-project/
sudo: required
dist: trusty

env:
    global:
        - LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/dependencies/libcsv/.libs
        - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
        - GENOMICSDB_BUILD_DIR=$TRAVIS_BUILD_DIR/build
        - GENOMICSDB_INSTALL_DIR=$GENOMICSDB_BUILD_DIR/install
        - PATH=$GENOMICSDB_INSTALL_DIR/bin:$TRAVIS_BUILD_DIR/bin:$PATH
        - GENOMICSDB_RELEASE_VERSION=0.6.2
        - CLASSPATH=$GENOMICSDB_INSTALL_DIR/bin/genomicsdb-${GENOMICSDB_RELEASE_VERSION}-jar-with-dependencies.jar:$GENOMICSDB_BUILD_DIR/target/genomicsdb-${GENOMICSDB_RELEASE_VERSION}-examples.jar:.

language: python
python: "3.4"

install:
    #Install dependencies
    - sudo pip install -U pytest>=3.0.7
    - sudo pip install -U pylint>=1.7.1
    - sudo pip install -U PyVCF
    - pip list installed
    
    - sudo apt-get -y install lcov mpich zlib1g-dev libssl-dev rsync cmake
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo add-apt-repository -y ppa:openjdk-r/ppa
    - sudo apt-get update -q
    - sudo apt-get install g++-4.9 -y
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 60
    - sudo apt-get -y install openjdk-8-jdk icedtea-plugin
    - jdk_switcher use openjdk8
    - echo $JAVA_HOME
    - export PATH=$JAVA_HOME/bin:$PATH
    - which javac && javac -version
    - which java && java -version
    #Copy protobuf binaries
    - wget https://github.com/Intel-HLS/GenomicsDB/releases/download/0.4.0/protobuf-3.0.2-trusty.tar.gz -O protobuf-3.0.2-trusty.tar.gz
    - tar xzf protobuf-3.0.2-trusty.tar.gz && sudo rsync -a protobuf-3.0.2-trusty/ /usr/
    #Install libcsv
    - cd $TRAVIS_BUILD_DIR
    - wget -O dependencies/libcsv.tar.gz http://downloads.sourceforge.net/project/libcsv/libcsv/libcsv-3.0.3/libcsv-3.0.3.tar.gz
    - mkdir -p dependencies/libcsv && tar xzf dependencies/libcsv.tar.gz  -C dependencies/libcsv --strip-components=1 && cd dependencies/libcsv && ./configure && make
    - cd $TRAVIS_BUILD_DIR
    # install lcov to coveralls conversion + upload tool
    - gem install coveralls-lcov
    - mkdir -p $GENOMICSDB_BUILD_DIR
    
before_script:
    - cd $GENOMICSDB_BUILD_DIR && lcov --directory . --zerocounters

script:
    - pytest ./docker/vcf_combiner/usr/bin/combine_vcf.py
    - cd $GENOMICSDB_BUILD_DIR
    - cmake $TRAVIS_BUILD_DIR -DBUILD_JAVA=1 -DCMAKE_BUILD_TYPE=Coverage -DCMAKE_INSTALL_PREFIX=$GENOMICSDB_INSTALL_DIR -DLIBCSV_DIR=$TRAVIS_BUILD_DIR/dependencies/libcsv -DGENOMICSDB_RELEASE_VERSION=$GENOMICSDB_RELEASE_VERSION -DMAVEN_QU:IET=True
    - make -j 4 && make install && make test ARGS=-V
    
after_success:
    - cd $GENOMICSDB_INSTALL_DIR && lcov --list tests/coverage.info # debug before upload
    #- coveralls-lcov --repo-token ${COVERALLS_TOKEN} tests/coverage.info # uploads to coveralls
    - pylint ./docker/vcf_combiner/usr/bin/combine_vcf.py