#Adapted from http://gronlier.fr/blog/2015/01/adding-code-coverage-to-your-c-project/
sudo: required
dist: trusty

language: python
python: "3.4"

install:
    #Install dependencies
    - pip freeze
    - pip -V
    - pip install -r requirements.txt
    - pip freeze

script:
    - pylint $TRAVIS_BUILD_DIR/docker/vcf_combiner/usr/bin/combine_vcf.py
    - pytest $TRAVIS_BUILD_DIR/docker/vcf_combiner/usr/bin/combine_vcf.py
   