#Adapted from http://gronlier.fr/blog/2015/01/adding-code-coverage-to-your-c-project/
sudo: required
dist: trusty

install:
    #Install lcov and MPICH
    - sudo apt-get -y install lcov mpich zlib1g-dev libssl-dev
    # install lcov to coveralls conversion + upload tool
    - gem install coveralls-lcov

before_script:
    - lcov --directory . --zerocounters

script:
    - make BUILD=debug-coverage TILEDB_BUILD_NUM_THREADS=4 HTSLIB_BUILD_NUM_THREADS=4 -j 4
    - python tests/run.py 

after_success:
    - lcov --list tests/coverage.info # debug before upload
    #- coveralls-lcov --repo-token ${COVERALLS_TOKEN} tests/coverage.info # uploads to coveralls
